### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by maradonamania** [maradonamania/protospace-36256#1]
https://protospace-36256.herokuapp.com/

**Comment by snkw-works** [comment]
@maradonamania さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移するよう修正しましょう**
プロトタイプ名をクリックしても詳細ページに遷移できない状態です。

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
プロトタイプ詳細ページの投稿者名をクリックすると、トップページに遷移してしまいます。
<img width="1272" alt="スクリーンショット_2021-07-19_10_47_50" src="https://user-images.githubusercontent.com/54050089/126091438-b6505857-8c59-4b76-8512-84e658b353d2.png">

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by snkw-works** [comment]
@maradonamania さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
